### PR TITLE
Registration form improvements

### PR DESCRIPTION
**Pull request by ionut-tanasa**
* Changed `userForm` to `registerForm` for consistency
  * Added email validation using ng-pattern and regex
  * Added `password_confirmation` field
  * Checking if password and password_confirmation are the same
  * Centered "I already have an account"
  * Added some rows / cols @ register page
  * Changed form "title" to an h3 to stay in line with the other forms like forgot password
  * Updated password_confirmation input. Added password-verify directive
  * Updated test to reflect the new field
  * Added validation rule for password_confirmation field (AuthController#190)

### CODE REVIEW

**Comment by silverbux** [comment]
Hi, first thank you for the awesome PR's

Just some minor adjustments.

* fix line indention on register-form.component.html
* apply password-verify directive **reference**: [user-profile.component.html#L87](https://github.com/silverbux/laravel-angular-admin/blob/master/angular/app/components/user-profile/user-profile.component.html#L87)
* update register form test cases **reference**: [/tests/angular/app/components/register-form/register-form.component.spec.js](https://github.com/silverbux/laravel-angular-admin/blob/master/tests/angular/app/components/register-form/register-form.component.spec.js)

**Comment by ionut-tanasa** [comment]
@silverbux about indentation. Do you have some guidelines ? Like spaces before tabs, how many spaces and so on.

Because if I reformat the whole file I change pretty much everything.

**Comment by silverbux** [comment]
currently on HTML Files i still haven't set any standards or guidelines yet except for the typical code structuring, probably 2 space as indention will do for now.

**Comment by silverbux** [comment]
Was conflicting and had to merge manually **reference:** https://github.com/silverbux/laravel-angular-admin/commit/9f63fec52a439ede284b74905b442d2f40eed465

**Pull request closed without merging**
